baseURL = "https://hunger.dpat.in/"
languageCode = "en-US"
title = "HUNgarian ⇄ GERman"
theme = "ezhil"

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    name = "➢ What Is Here?"
    url = "/posts/intro/"
